### ISSUE TITLE
Failing to build python project

### ISSUE THREAD

**Issue by AdamKorcz** [google/clusterfuzzlite#104]
[This CFL setup](https://github.com/samuelcolvin/pydantic/pull/4287) is breaking in the build process on [this line](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/typing.py#L4).

The build works fine on OSS-Fuzz but fails to complete in the CI.

Stacktrace from [the log](https://github.com/samuelcolvin/pydantic/runs/7655925047?check_suite_focus=true#step:4:137):
```Compiling libFuzzer to /usr/lib/libFuzzingEngine.a...  done.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/atheris/__init__.py", line 17, in <module>
    from typing import List
  File "/src/pydantic/typing.py", line 4, in <module>
    from typing import (  # type: ignore
ImportError: cannot import name 'TYPE_CHECKING' from partially initialized module 'typing' (most likely due to a circular import) (/src/pydantic/typing.py)```

**Comment by jonathanmetzman** [comment]
Is this still a problem?
