### ISSUE TITLE
CFLite seems to report issues that are reproducible with the latest build

### ISSUE THREAD

**Issue by evverx** [google/clusterfuzzlite#71]
In https://github.com/evverx/elfutils/runs/4719892523?check_suite_focus=true CFlite reported an issue that as far as I can tell should be reproducible with the latest build:
```
2022-01-05T20:37:26.5170500Z gelf_xlate.h:48:1: runtime error: member access within misaligned address 0x7f08cf690007 for type 'Elf32_Dyn', which requires 4 byte alignment
2022-01-05T20:37:26.5171380Z 0x7f08cf690007: note: pointer points here
2022-01-05T20:37:26.5171925Z  46 01 02 01 80  00 00 ff 01 00 00 54 ff  ff 45 48 48 48 48 04 de  7f 45 27 4e 00 00 00 32  2b 00 48
2022-01-05T20:37:26.5172266Z              ^ 
2022-01-05T20:37:26.5446405Z     #0 0x57fa1a in Elf32_cvt_Dyn /src/elfutils/libelf/./gelf_xlate.h:48:1
2022-01-05T20:37:26.5447286Z     #1 0x57f180 in elf32_xlatetom /src/elfutils/libelf/elf32_xlatetom.c:104:7
2022-01-05T20:37:26.5448229Z     #2 0x53ff9c in dwfl_segment_report_module /src/elfutils/libdwfl/dwfl_segment_report_module.c:848:20
2022-01-05T20:37:26.5455169Z     #3 0x4bad4d in dwfl_core_file_report /src/elfutils/libdwfl/core-file.c:563:17
2022-01-05T20:37:26.5456621Z     #4 0x4b3a22 in LLVMFuzzerTestOneInput /src/elfutils/tests/fuzz-dwfl-core.c:47:7
2022-01-05T20:37:26.5459860Z     #5 0x43d953 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp
2022-01-05T20:37:26.5461352Z     #6 0x43d13a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) cxa_noexception.cpp
2022-01-05T20:37:26.5462476Z     #7 0x43e6e9 in fuzzer::Fuzzer::MutateAndTestOne() cxa_noexception.cpp
2022-01-05T20:37:26.5463658Z     #8 0x43f3b5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
2022-01-05T20:37:26.5464944Z     #9 0x42eccf in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
2022-01-05T20:37:26.5466365Z     #10 0x457bf2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
2022-01-05T20:37:26.5467683Z     #11 0x7f08cf7150b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2022-01-05T20:37:26.5468709Z     #12 0x407d4d in _start (build-out/fuzz-dwfl-core+0x407d4d)
2022-01-05T20:37:26.5469214Z 
2022-01-05T20:37:26.5470037Z DEDUP_TOKEN: Elf32_cvt_Dyn--elf32_xlatetom--dwfl_segment_report_module
2022-01-05T20:37:26.5471320Z SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior gelf_xlate.h:48:1 in 
2022-01-05T20:37:26.5472764Z MS: 1 CrossOver-; base unit: a17f7d5db59b0763f7cd80ba8193f447f8e454a6
2022-01-05T20:37:26.5474409Z artifact_prefix='/tmp/tmp11sdfotu/'; Test unit written to /tmp/tmp11sdfotu/crash-db46ee9027b1d3bc81d4a4d57752de3c4f841df8
2022-01-05T20:37:26.5475543Z stat::number_of_executed_units: 100496
2022-01-05T20:37:26.5476101Z stat::average_exec_per_sec:     3349
2022-01-05T20:37:26.5476600Z stat::new_units_added:          1627
2022-01-05T20:37:26.5477103Z stat::slowest_unit_time_sec:    0
2022-01-05T20:37:26.5477594Z stat::peak_rss_mb:              44
2022-01-05T20:37:26.5707319Z 2022-01-05 20:37:26,569 - root - INFO - Fuzzer: fuzz-dwfl-core. Detected bug.
2022-01-05T20:37:26.5708979Z 2022-01-05 20:37:26,570 - root - INFO - Trying to reproduce crash using: /tmp/tmp11sdfotu/crash-db46ee9027b1d3bc81d4a4d57752de3c4f841df8.
2022-01-05T20:37:27.1111894Z 2022-01-05 20:37:27,110 - root - INFO - Reproduce command returned: 77. Reproducible on /github/workspace/build-out/fuzz-dwfl-core.
2022-01-05T20:37:27.1118804Z 2022-01-05 20:37:27,111 - root - INFO - Crash is reproducible.
2022-01-05T20:37:27.1213265Z 2022-01-05 20:37:27,120 - root - INFO - Trying to downloading previous build fc6455f2d50154ac7f4436bc1be3d02fd998b115.
2022-01-05T20:37:28.6243943Z 2022-01-05 20:37:28,623 - root - INFO - Done downloading previous build.
2022-01-05T20:37:28.6246347Z 2022-01-05 20:37:28,623 - root - INFO - Trying to reproduce crash using: /tmp/tmp11sdfotu/crash-db46ee9027b1d3bc81d4a4d57752de3c4f841df8.
2022-01-05T20:37:28.8747938Z 2022-01-05 20:37:28,874 - root - INFO - Reproduce command returned: 0. Not reproducible on /github/workspace/cifuzz-prev-build/fuzz-dwfl-core.
```
The action is relatively standard in https://github.com/evverx/elfutils/pull/53 apart from `REPORT_OOMS: false`

**Comment by evverx** [comment]
Sorry. My bad. By analogy with https://github.com/google/oss-fuzz/pull/7092 I turned on the alignment check there but since the latest build wasn't built with that check it doesn't fail. I need to rebuild the fuzzers with the alignment check.
